// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRrQgAHspOLGRUfw-jjUCmTRYjKXTj0fU',
    appId: '1:129790523460:web:fea201beae0215aaf7a411',
    messagingSenderId: '129790523460',
    projectId: 'poddy-caster-0001',
    authDomain: 'poddy-caster-0001.firebaseapp.com',
    storageBucket: 'poddy-caster-0001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9ZR_84r2dFvm33I4WJH15On5KtnHML4',
    appId: '1:129790523460:android:34ecce37b3fb3955f7a411',
    messagingSenderId: '129790523460',
    projectId: 'poddy-caster-0001',
    storageBucket: 'poddy-caster-0001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGQLRZmQrPqhl8zbA7Lf0yC3RaSf1UIO8',
    appId: '1:129790523460:ios:7a5930e68deddf8df7a411',
    messagingSenderId: '129790523460',
    projectId: 'poddy-caster-0001',
    storageBucket: 'poddy-caster-0001.appspot.com',
    iosClientId: '129790523460-t2vb3kiki49osb3rg8e6u8vao52psqs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.poddyCaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGQLRZmQrPqhl8zbA7Lf0yC3RaSf1UIO8',
    appId: '1:129790523460:ios:7a5930e68deddf8df7a411',
    messagingSenderId: '129790523460',
    projectId: 'poddy-caster-0001',
    storageBucket: 'poddy-caster-0001.appspot.com',
    iosClientId: '129790523460-t2vb3kiki49osb3rg8e6u8vao52psqs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.poddyCaster',
  );
}
